### 服务端口号
server:
  port: 8100


eureka:
  instance:
  ### 注册中心Ip地址
    hostname: 127.0.0.1
  client:
    service-url:
### hostname
      defaultZone: http://localhost:8100/eureka/
### 因为自己是注册中心，是否需要将自己注册给自己的注册中心（集群的时候是需要为true）
    register-with-eureka: false
### 因为自己是注册中心，不需要检索服务信息
    fetch-registry: false

