server:
  port: 8001
spring:
  application:
    name: spring-cloud-stream-any
  cloud:
    stream:
      #配置默认的binder
      default-binder: pos
      binders:
        scm:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                # 连接到scm的host和exchange
                virtual-host: scm
        pos:
          type: rabbit
          environment:
              spring:
                rabbitmq:
                  # 连接到pos的host和exchange
                  virtual-host: pos
        shop:
          type: rabbit
          environment:
              spring:
                rabbitmq:
                  # 连接到shop的host和exchange
                  virtual-host: shop
      bindings:
        #------消息消费者------
        order_set_start_produce_input:
          binder: pos
          destination: POS_ORDER_SET_STRAT_PRODUCE
          group: pos_grop

        #门店ID为1的消费者：
        shop_consumer_input_1:
          binder: shop
          destination: POS_ORDER_SET_STRAT_PRODUCE
          group: shop_1_grop
        #------消息生产---------
        #集单开始生产通知生产
        order_set_start_produce_output:
          binder: pos
          destination: POS_ORDER_SET_STRAT_PRODUCE

      rabbit:
        bindings:
          #集单开始生产消费者
          order_set_start_produce_input:
            consumer:
              exchangeType: topic
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: POS_ORDER_SET_STRAT_PRODUCE_POS_DLX
          # 门店1的消费者
          shop_consumer_input_1:
            consumer:
              exchangeType: topic
              autoBindDlq: true
              republishToDlq: true
              deadLetterExchange: POS_ORDER_SET_STRAT_PRODUCE_SHOP_1_DLX
              bindingRoutingKey: 1
              deadLetterRoutingKey: 1
           #生产者配置
          order_set_start_produce_output:
            producer:
              exchangeType: topic
              routingKeyExpression: headers.shopId
            # routingKeyExpression: headers['shopId']