###会员项目的端口号
server:
  port: 8010
### 服务的别名-服务注册到注册中心的名称
spring:
  application:
    name: member
eureka:
  client:
    service-url:
      ### 当前会员服务注册到Eureka服务
      defaultZone: http://localhost:8100/eureka
      ### 需要将我的服务注册到Eureka 上
    register-with-eureka: true
    ###需要检索服务
    fetch-registry: true