##订单服务端口号
server:
  port: 8001
spring:
  application:
    name: order
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    ### 需要将我的服务注册到Eureka 上
    register-with-eureka: true
    fetch-registry: true