eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/
  instance:
    prefer-ip-address: true
turbine:
  aggregator:
    cluster-config: default
  appConfig: provider-service,hello-service
  clusterNameExpression: new String('default')