server:
  port: 8011
spring:
  application:
    name: feign-gzip

logging:
  level:
    cn.springcloud.book.feign.service.HelloFeignService: debug


#feign:
#  compression:
#    request:
#      enabled: true
#      mime-types: text/xml,application/xml,application/json # 配置压缩支持的MIME TYPE
#      min-request-size: 2048  # 配置压缩数据大小的下限
#    response:
#      enabled: true # 配置响应GZIP压缩
feign:
  client:
    config:
      #需要配置的FeignName
      feignName:
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000 # 读超时时间设置
        loggerLevel: full # 配置Feign的日志级别
        erroerDecorder: com.example.SimpleErrorDecorder # Feign的错误解码器
        retryer: com.example.SimpleRetryer #配置充实
        requestInterceptors: #配置拦截器
          -com.example.FooRequestInerceptor
          -com.example.BarRequestInterceptor
        decode404: flase
        encoder: com.example.SimpleEncoder #Fegin的编码器
        decoder: com.example.SimpleDecoder # Feign的解码器
        contract: com.example.SimpleContract # Feign的contract配置


